### ISSUE TITLE
Разминаване на имена на канали във Vivacom TV GO

### ISSUE THREAD

**Issue by ignisf** [harrygg/EPG#4]
Здравейте,

Наблюдавам следните разминавания между присъстващите в vivacom.epg.xml.gz канали и предоставеното от TV GO (не знам дали BNT1 и Европа не са в резултат от езикови настройки на профила ми):

| vivacom.epg.xml.gz  | TV GO |
| ------------- | ------------- |
| БНТ 1  | BNT 1 HD  |
| bTV  | bTV HD  |
| bTV Comedy | bTV Comedy HD  |
| bTV Cinema  | bTV Cinema HD  |
| bTV Action | bTV Action HD  |
| bTV Lady | bTV Lady HD  |
| RING BG  | RING HD  |
| Nova Sport  | Nova Sport HD  |
| Travel Channel  | Travel Ch. HD  |
| ТВ Европа | TV Evropa  |

Липсващи от vivacom.epg.xml.gz, но присъстващи в epg.xml.gz:

- Euronews (в TV GO е Euronews HD)
- BSTV
- FilmBox Extra (в TV GO е FilmBox Extra HD)

Поздрави

**Comment by harrygg** [comment]
Ок. Промените в този проект са незначителни. Имената се настройват в https://github.com/harrygg/plugin.video.vivatvgo/blob/master/resources/map.json от където се четат и запазват в плейлистата генерирана от vivatvgo адона. Файла там е ъпдейтнат с новите имена. 

За в бъдеще работим над ново приложение за генериране на ЕПС, което ще генерира справочник в зависимост от каналите на отделните доставчици и техните имена. (WiP)
