### ISSUE TITLE
Как да....

### ISSUE THREAD

**Issue by TopperBG** [harrygg/EPG#6]
... помогнем със сайта? Общността е готова за подкрепа.

**Comment by harrygg** [comment]
Ами например Трябва ни предложения за читав и не прекалено скъп хостинг. Без български, че те са изнудвачи.

**Comment by TopperBG** [comment]
https://coolicehost.com/
https://gcore.com/
Комюнитито може да събере средства за един хостинг, пък бил и той Superhosting.bg

**Comment by ggets** [comment]
Какъв трафик се очаква? Мога да хостна ако не е нещо много изискващо.

**Comment by harrygg** [comment]
Трафика е макс 100 човека на ден :) За момента намерихме вариант и няма
нужда.

**Comment by NicoxDJ** [comment]
https://www.asurahosting.com

Ползвам го над 3 години. Доста съм доволен.
