### ISSUE TITLE
bulgaria epg dont work

### ISSUE THREAD

**Issue by gio299** [harrygg/EPG#8]
https://raw.githubusercontent.com/harrygg/EPG/master/epg.xml.gz

**Comment by harrygg** [comment]
The server where this is hosted is down and requires manual restart, but unfortunately there is no one around to do it. I’ll see how we can fix it remotely.

**Comment by hristo-genev** [comment]
fixed

**Comment by gio299** [comment]
THANKS!!!!!!!!!!
